alias e='emacs'
alias c='rm *~ *#'
alias gst='git status '
alias gp='git push '
alias gpo='git push origin '
alias gpom='git push origin master '
alias gd='git diff '
alias gc='git commit '
alias gm='git merge '
alias logincarver='ssh arbenson@carver.nersc.gov'
export EDITOR=emacs
export GIT_EDITOR=emacs